cache-time-seconds: 10

tool-types:
  SWORD:
    - 'WOODEN_SWORD'
    - 'STONE_SWORD'
    - 'IRON_SWORD'
    - 'GOLDEN_SWORD'
    - 'DIAMOND_SWORD'
    - 'NETHERITE_SWORD'
  PICKAXE:
    - 'WOODEN_PICKAXE'
    - 'STONE_PICKAXE'
    - 'IRON_PICKAXE'
    - 'GOLDEN_PICKAXE'
    - 'DIAMOND_PICKAXE'
    - 'NETHERITE_PICKAXE'
  SHEARS:
    - 'SHEARS'